apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: distroless
data:
  nginx.conf: |
    worker_processes  auto;

    events {
      worker_connections  1024;
    }

    http {
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /dev/stdout main;
      error_log   /dev/stderr warn;

      sendfile on;

      server {
        listen 80;
        server_name _;

        location / {
          return 200 'ok\n';
        }
      }
    }
