apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: distroless
  labels:
    app: nginx-distroless
spec:
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless:latest
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
      readOnly: true
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
