apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homework-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hw
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/k8s/pv/homework-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1
