apiVersion: v1
kind: Secret
metadata:
  name: monitoring-service-account-token
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: monitoring
type: kubernetes.io/service-account-token
data:
  token: |
    ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrVmhXVlpoWDBWc1NrTmhaWFJpVm1OMVpUSndU
    Vjh6ZGpWRE9VWkRUazVTUzFKMFZqbHFaalZQYUZraWZRLmV5SmhkV1FpT2xzaWFIUjBjSE02THk5
    cmRXSmxjbTVsZEdWekxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3aVhTd2laWGh3
    SWpveE56VTNOREEyT1RBMExDSnBZWFFpT2pFM05UY3lNelF4TURRc0ltbHpjeUk2SW1oMGRIQnpP
    aTh2YTNWaVpYSnVaWFJsY3k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzSWl3aWFu
    UnBJam9pWVdNMVpqZGpPV010TVRNNU1pMDBOVE0xTFdJMVlUZ3RPR0V6TkdVNVpUSmhPVE5rSWl3
    aWEzVmlaWEp1WlhSbGN5NXBieUk2ZXlKdVlXMWxjM0JoWTJVaU9pSm9iMjFsZDI5eWF5SXNJbk5s
    Y25acFkyVmhZMk52ZFc1MElqcDdJbTVoYldVaU9pSnRiMjVwZEc5eWFXNW5JaXdpZFdsa0lqb2la
    bVV3T0RZMU16WXRaVFU1WXkwMFpHTXhMV0l4WVRVdFpHTmxZVE15TXpJNVlqZzFJbjE5TENKdVlt
    WWlPakUzTlRjeU16UXhNRFFzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERw
    b2IyMWxkMjl5YXpwdGIyNXBkRzl5YVc1bkluMC5OMUtNUGlhTkcxSzkzZTVfWWlqOVdrZV9PbmlB
    LWEyUERrbFVDTVRabHJGT0daalFPQU1BdHB5UUJQWDAxZnRHX0RQLTNnQ2pSdmZzaGtEWHdtZm5W
    ZFliZkJ1UDBhcDE2aWlwZjRHSGFXQUlwYU5PazlMdFlKWFh5RjVmVmRGRDZmZFdMMFRvWHdSVlRI
    WVdxT1RGRVVyaTczSms1dlM3dGhRSG80WU5LQVpxQlFmOFhuTEJHQnU3RDlWU2RQTHc0RDRHWVVy
    d21EbnptWHVTbVE5STVJRmFibXFGX0Jqa2xfZXpBVFZUREdkRmYzOUFja0ljSEdhRDNoOGJXbU8z
    NUlvMGd0OTNBZU52eVJULUFYOTVmYmxJaXRGNWNSTHpOU21sQjZWbjdDblBYZHlkdWZ5Y21JNGJH
    dk40QzBQdmNnODdFWC1ZYkpGazFmTi1TU19uelE=