server:
  replicas: 3
  ha:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      storage "consul" {
        address = "consul-server.consul.svc.cluster.local:8500"
        path    = "vault/"
      }

      disable_mlock = true

  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: yc-network-hdd

  disruptionBudget:
    enabled: true
    maxUnavailable: 1

  service:
    type: ClusterIP

ui:
  enabled: true
  serviceType: ClusterIP
