apiVersion: v1
kind: Pod
metadata:
  name: vault-curl-check
  namespace: vault
spec:
  serviceAccountName: vault-auth
  restartPolicy: Never
  containers:
  - name: curl
    image: curlimages/curl:8.9.1
    command: ["/bin/sh","-lc"]
    args:
      - |
        echo "pod is ready; sleeping..."
        sleep 3600
