apiVersion: v1
kind: Pod
metadata:
  name: vault-auth-test
  namespace: vault
spec:
  serviceAccountName: vault-auth
  restartPolicy: Never
  containers:
    - name: runner
      image: alpine:3.20
      command:
        - sh
        - -lc
        - |
          set -eu
          apk add --no-cache curl jq >/dev/null
          VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"
          SA_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
          echo "Logging in to Vault with Kubernetes auth..."
          LOGIN_JSON="$(curl -sS -X POST \
            -H 'Content-Type: application/json' \
            --data "{\"jwt\":\"${SA_TOKEN}\",\"role\":\"otus-role\"}" \
            "${VAULT_ADDR}/v1/auth/kubernetes/login")"
          echo "$LOGIN_JSON" | jq '.'
          VAULT_TOKEN="$(echo "$LOGIN_JSON" | jq -r '.auth.client_token')"
          echo "Reading secret otus/cred..."
          curl -sS -H "X-Vault-Token: ${VAULT_TOKEN}" \
            "${VAULT_ADDR}/v1/otus/cred" | jq '.'
          echo "Done. Sleeping to keep logs visible."
          sleep 3600
