apiVersion: v1
kind: Pod
metadata:
  name: vault-k8s-login
  namespace: vault
spec:
  serviceAccountName: vault-auth
  restartPolicy: Never
  containers:
  - name: vault
    image: hashicorp/vault:1.20.4
    env:
    - name: VAULT_ADDR
      value: http://vault.vault.svc:8200
    command: ["/bin/sh","-lc"]
    args:
      - |
        echo "==> Trying 'vault login -method=kubernetes role=otus-role'..."
        vault login -method=kubernetes role=otus-role || true
        echo "==> If success above, try reading secret (KV v2 path):"
        vault kv get otus/cred || true
        sleep 3600
