apiVersion: v1
kind: Pod
metadata:
  name: vault-auth-test
  namespace: vault
spec:
  serviceAccountName: vault-auth
  restartPolicy: Never
  containers:
  - name: curl
    image: curlimages/curl:8.9.1
    command: ["sh","-lc","sleep infinity"]