image:
  registry: docker.io
  repository: grafana/grafana

adminUser: admin
adminPassword: "ad232323232323"   

nodeSelector:
  node-role: "infra"
tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: true
        jsonData:
          maxLines: 1000

service:
  type: ClusterIP

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
